name: Deploy VitePress site to Pages

on:
  push:
    branches:
      - main # 在 main 分支有新的提交时触发

  pull_request:
    branches:
      - main # 在有 PR 提交到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # 增加此权限，用于在 PR 中添加评论

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build VitePress site
        run: npm run docs:build

      - name: Archive build output
        uses: actions/upload-artifact@v3
        with:
          name: vitepress-build-output
          path: docs/.vitepress/dist

  deploy-to-pages:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    # 仅当合并到 main 分支时才进行部署
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: vitepress-build-output
          path: docs/.vitepress/dist

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # 使用 v3，因为 v4 集成更强，但 v3 更稳定
        with:
          path: docs/.vitepress/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2